version: "3.8"
services:
  api:
    build: ./backend
    container_name: apic
    # ports:
    #   - '5000:5000'
    network_mode: host
    volumes:
      - ./backend:/app
      - ./app/node_modules
    command: npm run start
  client:
    build: ./client
    container_name: clientc
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  cppserver:
    build: ./cppserver
    container_name: cppapic
    network_mode: host